import { ai, db, error, json, requireAuth, router } from '@appdeploy/sdk';

type PlanId = 'FREE'|'NHAN_HOA'|'NHAT_VAN'|'DIA_LOI'|'THIEN_THOI'|'SONG_MENH'|'TOAN_DIEN'|'PREMIUM';
type AccessRecord = { userId:string; webId:string; role:'free'|'vip'|'admin'; plan:PlanId; enabled:boolean; startsAt:string; expiresAt:string|null; createdAt:string; updatedAt:string };
type AccessIndexRecord = AccessRecord & { accessTable:string; accessRecordId:string; email?:string; name?:string };

const interpretationSchema = { type:'object', properties:{ overview:{type:'string'}, keyFindings:{type:'array',items:{type:'string'}}, strengths:{type:'string'}, cautions:{type:'string'}, domains:{type:'array',items:{type:'object',properties:{title:{type:'string'},analysis:{type:'string'}},required:['title','analysis']}}, timing:{type:'string'}, practical:{type:'string'}, limits:{type:'string'} }, required:['overview','keyFindings','strengths','cautions','domains','timing','practical','limits'] };
const dreamSchema = { type:'object', properties:{ summary:{type:'string'}, elements:{type:'array',items:{type:'string'}}, emotions:{type:'array',items:{type:'string'}}, narrative:{type:'string'}, emotionalDynamics:{type:'string'}, symbolContext:{type:'string'}, modern:{type:'string'}, neuroscience:{type:'string'}, jung:{type:'string'}, freud:{type:'string'}, synthesis:{type:'string'}, confidence:{type:'string'}, questions:{type:'array',items:{type:'string'}}, caution:{type:'string'} }, required:['summary','elements','emotions','narrative','emotionalDynamics','symbolContext','modern','neuroscience','jung','freud','synthesis','confidence','questions','caution'] };
const totalFortuneSchema = { type:'object', properties:{ daySummary:{type:'string'}, monthSummary:{type:'string'}, convergence:{type:'array',items:{type:'string'}}, conflicts:{type:'array',items:{type:'string'}}, domains:{type:'array',items:{type:'object',properties:{title:{type:'string'},day:{type:'string'},month:{type:'string'},sources:{type:'array',items:{type:'string'}}},required:['title','day','month','sources']}}, dayFlow:{type:'array',items:{type:'object',properties:{period:{type:'string'},analysis:{type:'string'},sources:{type:'array',items:{type:'string'}}},required:['period','analysis','sources']}}, monthMarkers:{type:'array',items:{type:'object',properties:{period:{type:'string'},analysis:{type:'string'},sources:{type:'array',items:{type:'string'}}},required:['period','analysis','sources']}}, practical:{type:'array',items:{type:'string'}}, limits:{type:'array',items:{type:'string'}} }, required:['daySummary','monthSummary','convergence','conflicts','domains','dayFlow','monthMarkers','practical','limits'] };

const moduleGuidance: Record<string,string> = {
  tuvi:'Tử Vi: luận Mệnh/Thân, tam phương tứ chính, chính-phụ tinh, Tuần/Triệt, Tứ Hóa, công việc, tài lộc, tình cảm-gia đạo, sức khỏe theo nghĩa xu hướng, nhà cửa, con cái và vận khi dữ liệu HIỂN THỊ có hỗ trợ. Phân biệt bản mệnh với đại/tiểu/lưu vận. Không tự thêm sao.',
  calendar:'Phong thủy ngày: giải nghĩa Can Chi, trực/thần, Yi-Ji, xung sát và phương vị đã tính. Nêu việc hợp/không hợp theo chính dữ liệu màn hình; không tự tạo giờ tốt, màu hay tuổi hợp nếu chưa có.',
  battrach:'Bát Trạch: chỉ luận khi màn hình đã có quái mệnh/hướng/rule kết quả. Nếu engine đang khóa hoặc chỉ có input/nguồn sách thì phải nói chưa đủ dữ liệu, tuyệt đối không tự tính quái số/hướng cát hung.',
  iching:'Kinh Dịch/Lục Hào: bám Quẻ chủ-Hỗ-Biến, hào động, Thế-Ứng, Nhật thần, Nguyệt lệnh, Lục Thân, Nạp Giáp, Tuần Không, vượng suy và thần sát đang hiển thị. Không tự chọn Dụng thần/Nguyên-Kỵ thần nếu engine chưa khóa. Luận diễn biến, thuận-nghịch, điểm chuyển và thời điểm chỉ khi dữ liệu hỗ trợ.',
  bazi:'Bát Tự: bám 4 trụ, Nhật chủ, Nguyệt lệnh, tàng can, Thập thần, Trường sinh, Nạp âm và tương tác đã tính. Không tự phán Cường/Nhược, Cách cục, Dụng/Hỷ/Kỵ nếu màn hình ghi các lớp đó chưa khóa. Có thể giải thích ý nghĩa cấu trúc và nêu điều cần kiểm tra tiếp.',
  qimen:'Kỳ Môn: bám Âm/Dương Độn, cục, địa bàn, Cửu tinh/Bát môn, Tuần thủ, Trực Phù/Trực Sử và các rule đã hiện. Nếu Thiên/Nhân/Thần bàn động chưa dựng thì không được luận như đã có đủ bàn.',
  astrology:'Chiêm tinh hiện tại: bám vị trí hành tinh/cung/độ đã tính; mô tả chủ đề biểu tượng, không tự tạo góc chiếu, houses, ASC/MC nếu không hiển thị.',
  sky:'Huyền Thiên Tinh Bàn: giải thích vùng trời, hướng nhìn, thiên thể, azimuth/altitude và decan zodiacal đang hiển thị. Không đánh đồng decan zodiacal 10° với stellar decans Ai Cập cổ.',
  numerology:'Thần số học Pythagoras: bám đúng các số đã tính như đường đời, ngày sinh, thái độ, biểu đạt, linh hồn, nhân cách; nêu điểm giao nhau/mâu thuẫn giữa chúng. Không tự thêm hệ Chaldean hay chỉ số chưa tính.',
  natal:'Bản đồ sao: bám vị trí hành tinh/cung/độ đang có. Nếu app chưa có ASC/MC/houses/aspects thì nêu rõ và không tự suy ra.'
};
const planModules: Record<PlanId,string[]> = { FREE: [], NHAN_HOA: ['human'], NHAT_VAN: ['calendar'], DIA_LOI: ['tuvi'], THIEN_THOI: ['bazi'], SONG_MENH: ['tuvi','bazi'], TOAN_DIEN: ['human','calendar','tuvi','bazi'], PREMIUM: ['human','calendar','tuvi','bazi','battrach','iching','qimen','astrology','sky','numerology','natal'] };
const planRules: Record<PlanId,string> = { FREE:'Chỉ dùng engine tính/lập dữ liệu. Không được sinh nội dung luận giải AI.', NHAN_HOA:'Chỉ luận tình huống và con người từ dữ liệu Nhân Hòa được cung cấp.', NHAT_VAN:'Chỉ luận thời điểm hành động từ dữ liệu ngày đã tính.', DIA_LOI:'Chỉ dùng lớp Tử Vi.', THIEN_THOI:'Chỉ dùng lớp Bát Tự.', SONG_MENH:'Có Địa Lợi + Thiên Thời.', TOAN_DIEN:'Có Nhân Hòa + Nhật Vận + Địa Lợi + Thiên Thời.', PREMIUM:'Có toàn bộ quyền luận giải hiện có và lớp cao cấp.' };
function active(record:AccessRecord) { return record.enabled && (!record.expiresAt || new Date(record.expiresAt).getTime() > Date.now()) && new Date(record.startsAt).getTime() <= Date.now(); }
function canInterpret(record:AccessRecord,module:string) { if(record.role==='admin') return true; if(!active(record)) return false; return (planModules[record.plan] || []).includes(module); }
function ruleFor(record:AccessRecord) { if(record.role==='admin') return 'ADMIN: có toàn bộ entitlement và toàn bộ rule pack của mọi gói. Vẫn phải tuân thủ rule tính toán, giới hạn dữ liệu và không được tự bịa dữ kiện.'; return planRules[record.plan]; }
const ROOT_ADMIN_WEB_IDS = new Set(['HH-2C482676DD','HH-EEF97E4044']);
const ADMIN_EMAILS = new Set(['kinrennie@gmail.com']);

async function syncAccessIndex(record:AccessRecord & { id?:string }, table:string, identity?:{email?:string;name?:string}) { if(!record.id) return; const { items } = await db.list<AccessIndexRecord>('access-index',{limit:200}); const found = items.find(item => item.userId === record.userId); const indexed: AccessIndexRecord = { ...record, accessTable:table, accessRecordId:record.id, email:identity?.email ?? found?.email, name:identity?.name ?? found?.name }; delete (indexed as {id?:string}).id; if(found) await db.update('access-index',[{id:found.id,record:indexed}]); else await db.add('access-index',[indexed]); }
async function requireAdminAccess(userId:string) { const access = await getAccess(userId); if(access.role !== 'admin' || !active(access)) return null; return access; }
async function getAccess(userId:string, identity?:{email?:string;name?:string}) { const table = `access:${userId}`; const { items } = await db.list<AccessRecord>(table,{limit:1}); const derivedWebId = `HH-${userId.replace(/-/g,'').slice(0,10).toUpperCase()}`; const normalizedEmail = identity?.email?.trim().toLowerCase(); const isRootAdmin = ROOT_ADMIN_WEB_IDS.has(derivedWebId); const isEmailAdmin = !!normalizedEmail && ADMIN_EMAILS.has(normalizedEmail); const shouldBeAdmin = isRootAdmin || isEmailAdmin; if(items[0]) { const current = items[0]; if(shouldBeAdmin && (current.role !== 'admin' || current.plan !== 'PREMIUM' || !current.enabled)) { const updated: AccessRecord = {...current,webId:derivedWebId,role:'admin',plan:'PREMIUM',enabled:true,expiresAt:null,updatedAt:new Date().toISOString()}; const [ok] = await db.update(table,[{id:current.id,record:updated}]); if(!ok) throw new Error('Không thể kích hoạt Admin gốc.'); const result = {...updated,id:current.id}; await syncAccessIndex(result,table,identity); return result; } await syncAccessIndex(current,table,identity); return current; } const now = new Date().toISOString(); const record:AccessRecord = {userId,webId:derivedWebId,role:shouldBeAdmin?'admin':'free',plan:shouldBeAdmin?'PREMIUM':'FREE',enabled:true,startsAt:now,expiresAt:null,createdAt:now,updatedAt:now}; const [id] = await db.add(table,[record]); if(!id) throw new Error('Không thể tạo hồ sơ quyền.'); const result = {...record,id}; await syncAccessIndex(result,table,identity); return result; }
export const handler = router({
  'GET /api/_healthcheck':[async()=>json({message:'Success'})],
  'GET /api/me':[requireAuth(),async(ctx)=>{const access=await getAccess(ctx.user!.userId,{email:ctx.user!.email,name:ctx.user!.name});return json({webId:access.webId,role:access.role,plan:access.plan,enabled:access.enabled,startsAt:access.startsAt,expiresAt:access.expiresAt,active:active(access),email:ctx.user!.email,name:ctx.user!.name});}],
  'GET /api/admin/access':[requireAuth(),async(ctx)=>{const admin=await requireAdminAccess(ctx.user!.userId); if(!admin) return error('Chỉ Admin mới có quyền quản lý tài khoản.',403); const {items}=await db.list<AccessIndexRecord>('access-index',{limit:200}); return json({items:items.map(({id,...item})=>item)});}],
  'PUT /api/admin/access':[requireAuth(),async(ctx)=>{const admin=await requireAdminAccess(ctx.user!.userId); if(!admin) return error('Chỉ Admin mới có quyền quản lý tài khoản.',403); const input=ctx.body as {webId?:string;email?:string;role?:'free'|'vip'|'admin';plan?:PlanId;enabled?:boolean;startsAt?:string;expiresAt?:string|null}; const webId=(input.webId||'').trim().toUpperCase(); const email=(input.email||'').trim().toLowerCase(); if(!webId&&!email)return error('Nhập ID web hoặc email.',400); const {items}=await db.list<AccessIndexRecord>('access-index',{limit:200}); const target=items.find(item=>(webId&&item.webId===webId)||(email&&item.email?.toLowerCase()===email)); if(!target)return error('Email/ID này chưa từng đăng nhập web nên chưa có hồ sơ để cấp quyền.',404); const updated:AccessRecord={...target,role:input.role??target.role,plan:input.plan??target.plan,enabled:input.enabled??target.enabled,startsAt:input.startsAt||target.startsAt,expiresAt:input.expiresAt===undefined?target.expiresAt:input.expiresAt,updatedAt:new Date().toISOString()}; const [ok]=await db.update(target.accessTable,[{id:target.accessRecordId,record:updated}]); if(!ok)return error('Không thể cập nhật quyền.',500); await syncAccessIndex({...updated,id:target.accessRecordId},target.accessTable); return json({ok:true,record:updated});}],
  'POST /api/interpret':[requireAuth(),async(ctx)=>{const input=ctx.body as {module?:string;snapshot?:string}; const module=input.module?.trim()??''; const snapshot=input.snapshot?.trim()??''; if(!moduleGuidance[module])return error('Module chưa hỗ trợ luận giải.',400); const access=await getAccess(ctx.user!.userId); if(!canInterpret(access,module))return error('Gói hiện tại chưa có quyền luận giải mục này.',403); if(snapshot.length<80)return error('Chưa có đủ kết quả để luận.',400); try{const result=await ai.generate({system:'Bạn là engine luận giải huyền học. Chỉ diễn giải dữ liệu snapshot, không tự bịa dữ kiện.',prompt:`MODULE: ${module}\nRULE: ${ruleFor(access)}\n${moduleGuidance[module]}\nSNAPSHOT:\n${snapshot.slice(0,18000)}`,schema:interpretationSchema,thinkingMode:'DEEP',temperature:.18,maxTokens:6000});return json(JSON.parse(result.text));}catch(err){console.error(err);return error('Không thể luận giải lúc này.',500);}}],
  'POST /api/total-fortune':[requireAuth(),async(ctx)=>{const access=await getAccess(ctx.user!.userId,{email:ctx.user!.email,name:ctx.user!.name}); if(access.role!=='admin'&&(access.role!=='vip'||!active(access)))return error('Tổng Vận là đặc quyền VIP.',403); const input=ctx.body as {profile?:{birthDate?:string;birthTime?:string};targetDate?:string;latitude?:number;longitude?:number;engineData?:Record<string,string>}; const layers=Object.entries(input.engineData||{}).map(([k,v])=>`[${k}]\n${v}`).join('\n\n'); try{const result=await ai.generate({system:'Chỉ tổng hợp dữ liệu engine đã tính; không tự tính hoặc bịa.',prompt:layers,schema:totalFortuneSchema,thinkingMode:'DEEP',temperature:.15,maxTokens:7000});return json(JSON.parse(result.text));}catch(err){console.error(err);return error('Không thể tổng hợp Tổng Vận lúc này.',500);}}],
  'POST /api/dreams/analyze':[requireAuth(),async(ctx)=>{const access=await getAccess(ctx.user!.userId); if(!canInterpret(access,'human'))return error('Gói hiện tại chưa có quyền phân tích nội dung này.',403); const input=ctx.body as {dream?:string;context?:string}; const dream=input.dream?.trim()??''; if(dream.length<20)return error('Giấc mơ quá ngắn để phân tích.',400); try{const result=await ai.generate({system:`Bạn là bộ phân tích giấc mơ. ${ruleFor(access)}`,prompt:dream,schema:dreamSchema,thinkingMode:'DEEP',temperature:.2,maxTokens:5200});return json(JSON.parse(result.text));}catch(err){console.error(err);return error('Không thể phân tích giấc mơ lúc này.',500);}}]
});